# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopsule < Formula
  desc "Decision-first, context-aware, portable memory system CLI"
  homepage "https://hopsule.com"
  version "0.9.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.9/hopsule-darwin-amd64.tar.gz"
      sha256 "1e0dbd0b2bf4f546ad97cbfe4182d814047703d37ca3ec74b12392160ff635a5"

      def install
        bin.install "hopsule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.9/hopsule-darwin-arm64.tar.gz"
      sha256 "674f0921849b957148867df7261070ffa86ce46f1bd5074cfeeac3f1ecabb82f"

      def install
        bin.install "hopsule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.9/hopsule-linux-amd64.tar.gz"
      sha256 "8397780f282c4c940b548ec95b964135e1b4e4ff07e58373fabbdbe473eab084"
      def install
        bin.install "hopsule"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.9/hopsule-linux-arm64.tar.gz"
      sha256 "86ac53152c52bf462b177b39713e18a2921ba28ddf50e9ffbf6543ec3621d33b"
      def install
        bin.install "hopsule"
      end
    end
  end

  test do
    system "#{bin}/hopsule", "--version"
  end
end
