# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopsule < Formula
  desc "Decision-first, context-aware, portable memory system CLI"
  homepage "https://hopsule.com"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.4/hopsule-darwin-amd64.tar.gz"
      sha256 "038992eb525d4d49cef6b31d35e967e869d1286fe8f8233bfb4517b9fef3a6ef"

      def install
        bin.install "hopsule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.4/hopsule-darwin-arm64.tar.gz"
      sha256 "591aa1444ce1abdc5d311210b29195e2166a2e0b185d854e9dc11e6bafeb295d"

      def install
        bin.install "hopsule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.4/hopsule-linux-amd64.tar.gz"
      sha256 "a5051b238d513dd75f19315b73002ea03f8a902307f57b1f79dd64bc4ad01c1e"
      def install
        bin.install "hopsule"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hopsule/cli-tool/releases/download/v0.9.4/hopsule-linux-arm64.tar.gz"
      sha256 "b5eb8a66a24f75ef2400fd0e071f540b156a3f0031cfb2eefa940a4b981883a6"
      def install
        bin.install "hopsule"
      end
    end
  end

  test do
    system "#{bin}/hopsule", "--version"
  end
end
